/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface": "#f6fafe",
        "secondary-fixed": "#90f5de",
        "surface-container-low": "#f0f4f8",
        "tertiary-container": "#596c7a",
        "on-tertiary-fixed": "#091e29",
        "primary": "#004ab7",
        "primary-container": "#1061e5",
        "outline": "#737786",
        "on-surface-variant": "#424654",
        "surface-container-high": "#e4e9ed",
        "surface-container": "#eaeef2",
        "inverse-on-surface": "#edf1f5",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#171c1f",
        "on-background": "#171c1f",
        "inverse-surface": "#2c3134",
        "on-secondary-fixed-variant": "#005144",
        "surface-tint": "#0056d2",
        "inverse-primary": "#b2c5ff",
        "surface-variant": "#dfe3e7",
        "on-secondary-fixed": "#00201a",
        "secondary": "#006b5b",
        "secondary-container": "#90f5de",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-container": "#e6eaff",
        "tertiary": "#415462",
        "background": "#f6fafe",
        "surface-container-highest": "#dfe3e7",
        "surface-dim": "#d6dade",
        "on-primary-fixed-variant": "#0040a1",
        "tertiary-fixed": "#d1e5f6",
        "surface-bright": "#f6fafe",
        "outline-variant": "#c2c6d7",
        "on-tertiary-fixed-variant": "#364956",
        "on-secondary-container": "#007261",
        "on-tertiary-container": "#d9edfe",
        "on-primary-fixed": "#001847",
        "primary-fixed-dim": "#b2c5ff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#73d8c2",
        "tertiary-fixed-dim": "#b5c9d9"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Public Sans"],
        "label": ["Public Sans"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}